In [2]:
import numpy as np

In [3]:
np.random.seed(0)

In [7]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))
x4 = np.random.randint(10, size=(3, 4, 5, 6))

In [10]:
print(f'Размерности: \n'
      f'x1 ndim = {x1.ndim}\n'
      f'x2 ndim = {x2.ndim}\n'
      f'x3 ndim = {x3.ndim}\n'
      f'x4 ndim = {x4.ndim}\n')
print(f'Размеры: \n'
      f'x1 shape = {x1.shape}\n'
      f'x2 shape = {x2.shape}\n'
      f'x3 shape = {x3.shape}\n'
      f'x4 shape = {x4.shape}\n')
print(f'Общий размер: \n'
      f'x1 size = {x1.size}\n'
      f'x2 size = {x2.size}\n'
      f'x3 size = {x3.size}\n'
      f'x4 size = {x4.size}\n')

Размерности: 
x1 ndim = 1
x2 ndim = 2
x3 ndim = 3
x4 ndim = 4

Размеры: 
x1 shape = (6,)
x2 shape = (3, 4)
x3 shape = (3, 4, 5)
x4 shape = (3, 4, 5, 6)

Общий размер: 
x1 size = 6
x2 size = 12
x3 size = 60
x4 size = 360



In [11]:
print(f'типы данных: \n'
      f'x1 dtype = {x1.dtype}\n'
      f'x2 dtype = {x2.dtype}\n'
      f'x3 dtype = {x3.dtype}\n'
      f'x4 dtype = {x4.dtype}\n')

типы данных: 
x1 dtype = int32
x2 dtype = int32
x3 dtype = int32
x4 dtype = int32



In [13]:
print(f'Прочее: \n'
      f'x1 itemsize = {x1.itemsize} bytes\n'
      f'x2 nbytes = {x2.nbytes} bytes')

Прочее: 
x1 itemsize = 4 bytes
x2 nbytes = 48 bytes


In [14]:
x1

array([3, 5, 2, 4, 7, 6])

In [15]:
x2

array([[8, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]])

In [16]:
x3

array([[[4, 3, 0, 3, 5],
        [0, 2, 3, 8, 1],
        [3, 3, 3, 7, 0],
        [1, 9, 9, 0, 4]],

       [[7, 3, 2, 7, 2],
        [0, 0, 4, 5, 5],
        [6, 8, 4, 1, 4],
        [9, 8, 1, 1, 7]],

       [[9, 9, 3, 6, 7],
        [2, 0, 3, 5, 9],
        [4, 4, 6, 4, 4],
        [3, 4, 4, 8, 4]]])

In [18]:
print(x4)

[[[[3 7 5 5 0 1]
   [5 9 3 0 5 0]
   [1 2 4 2 0 3]
   [2 0 7 5 9 0]
   [2 7 2 9 2 3]]

  [[3 2 3 4 1 2]
   [9 1 4 6 8 2]
   [3 0 0 6 0 6]
   [3 3 8 8 8 2]
   [3 2 0 8 8 3]]

  [[8 2 8 4 3 0]
   [4 3 6 9 8 0]
   [8 5 9 0 9 6]
   [5 3 1 8 0 4]
   [9 6 5 7 8 8]]

  [[9 2 8 6 6 9]
   [1 6 8 8 3 2]
   [3 6 3 6 5 7]
   [0 8 4 6 5 8]
   [2 3 9 7 5 3]]]


 [[[4 5 3 3 7 9]
   [9 9 7 3 2 3]
   [9 7 7 5 1 2]
   [2 8 1 5 8 4]
   [0 2 5 5 0 8]]

  [[1 1 0 3 8 8]
   [4 4 0 9 3 7]
   [3 2 1 1 2 1]
   [4 2 5 5 5 2]
   [5 7 7 6 1 6]]

  [[7 2 3 1 9 5]
   [9 9 2 0 9 1]
   [9 0 6 0 4 8]
   [4 3 3 8 8 7]
   [0 3 8 7 7 1]]

  [[8 4 7 0 4 9]
   [0 6 4 2 4 6]
   [3 3 7 8 5 0]
   [8 5 4 7 4 1]
   [3 3 9 2 5 2]]]


 [[[3 5 7 2 7 1]
   [6 5 0 0 3 1]
   [9 9 6 6 7 8]
   [8 7 0 8 6 8]
   [9 8 3 6 1 7]]

  [[4 9 2 0 8 2]
   [7 8 4 4 1 7]
   [6 9 4 1 5 9]
   [7 1 3 5 7 3]
   [6 6 7 9 1 9]]

  [[6 0 3 8 4 1]
   [4 5 0 3 1 4]
   [4 4 0 0 8 4]
   [6 9 3 3 2 1]
   [2 1 3 4 1 1]]

  [[0 7 8 4 3 5]
   [6 3 2 9 8 1]
   [4

In [19]:
x = np.arange(10)

In [20]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x[:5]

array([0, 1, 2, 3, 4])

In [22]:
x[0:5]

array([0, 1, 2, 3, 4])

In [23]:
x[5:]

array([5, 6, 7, 8, 9])

In [24]:
x[5:8]

array([5, 6, 7])

In [25]:
x[4:9:2]

array([4, 6, 8])

In [26]:
x[::2]

array([0, 2, 4, 6, 8])

In [27]:
x[1::2]

array([1, 3, 5, 7, 9])

In [28]:
x2

array([[8, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]])

In [29]:
x2[:2, :3]

array([[8, 8, 1],
       [7, 7, 8]])

In [30]:
x2[:, :2]

array([[8, 8],
       [7, 7],
       [5, 9]])

In [31]:
x2[:3,::2]

array([[8, 1],
       [7, 8],
       [5, 8]])

In [32]:
grid = np.arange(1, 10).reshape((3, 3))

In [33]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
x[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [36]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [37]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
y = x.copy()
z = x.copy()

In [39]:
_ = np.concatenate([x, y, z])

In [40]:
_

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
_ = np.vstack([x, y, z])

In [42]:
_

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
np.hstack([x, y, z])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x1, x2, x3 = np.split(x, [2, 5])

In [50]:
print(x1)
print(x2)
print(x3)

[0 1]
[2 3 4]
[5 6 7 8 9]


In [51]:
np.empty(4)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.39071870e-307])

In [52]:
np.random.seed(0)

def funk(vals):
    outp = np.empty(len(vals))
    for i in range(len(vals)):
        outp[i] = 1.0 / vals[i]
    return outp

In [55]:
big_array = np.random.randint(1, 100, size=100000)
%timeit funk(big_array)
%timeit print(1.0 / big_array)

223 ms ± 1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]

[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04

[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04

[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04

[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04

[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04

[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04

[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04

[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04

[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04      ]
[0.01282051 0.02857143 0.01219512 ... 0.01694915 0.01176471 0.04